---
version: "3.9"

services:
  nginx:
    image: "nginx:1.23.1"
    container_name: "router-nginx"
    restart: "always"
    volumes:
      - "./volumes/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 80:80


  api1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
          CONTAINER: FIRST
    ports:
      - 8080:8080
    restart: "always"

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONTAINER: SECOND
    ports:
      - 8081:8080
    restart: "always"

  api3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONTAINER: THIRD
    ports:
      - 8082:8080
    restart: "always"

networks:
  default:
    name: "global-nginx"
    driver: "bridge"
