---
version: "3.9"

services:
  nginx:
    image: "nginx:1.23.1"
    container_name: "router-nginx"
    restart: "always"
    volumes:
      - "./volumes/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 80:80

    depends_on:
      - api1
      - api2
      - api3
      - api4


  api1:
    container_name: "api1"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
          CONTAINER: FIRST
    entrypoint: ["uvicorn", "app.main:app", "--host=0.0.0.0", "--port=8080"]
    restart: "always"


  api2:
    container_name: "api2"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONTAINER: SECOND
    entrypoint: ["uvicorn", "app.main:app", "--host=0.0.0.0", "--port=8080"]
    restart: "always"


  api3:
    container_name: "api3"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONTAINER: THIRD
    entrypoint: ["uvicorn", "app.main:app", "--host=0.0.0.0", "--port=8080"]
    restart: "always"

  api4:
    container_name: "api4"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONTAINER: FOURTH
    entrypoint: [ "uvicorn", "app.main:app", "--host=0.0.0.0", "--port=8080" ]
    restart: "always"

